# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                    : "minimal-mistakes-jekyll"   #主题选项
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" #选择配色方案 "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"  

# Site Settings
locale                   : "zh-CN" #设备语言为中文
title                    : "Charlie的学习与生活" #设置标题
title_separator          : "-" #标题分隔符
subtitle                 : "Last Update 2021.12.08 | 78% Done" #副标题
name                     : "Charlie-TechBlog"
description              : "唯爱人与食物不可辜负"
url                      : "https://s975188062.github.io"
baseurl                  : # "/tree/master"
repository               : #"s975188062/s975188062.github.io"
teaser                   : #"/assets/images/background.png" #默认的文章缩略图 path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/blog_icon_charlie.ico"
masthead_title           : "Charlie的学习与生活" # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)
words_per_minute         : 100
comments:
  provider               :  "livere" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : #"charlie-techblog-com" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : # "master", "gh-pages"
  commitMessage          : "New comment by {fields.name}"
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : "lunr"
algolia:
  application_id         : "QB6HVGBSBA"
  index_name             : "dev_minimal-mistakes"
  search_only_api_key    : "9d5014e5bbc77372547bce778dfa5663"
  powered_by             : true
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "宋昌霖"
  avatar           : "/assets/images/head_photo.png"
  bio              : "唯爱人与美食不可辜负"
  location         : #"Beijing"
  email            : # "Schanglin@outlook.com"
  links:
    - label: " Charlie-TechBlog@outlook.com"
      icon: "fas fa-envelope fa-fw"
      url: mailto:Charlie-TechBlog@outlook.com
    - label: " 私房食谱"
      icon: "fas fa-book fa-fw"
      url: /recipe/
    - label: " Charlie的万事屋"
      icon: "fas fa-store-alt fa-fw"
      url: /pay4more/
    - label: " 博客更新日志"
      icon: "fas fa-clipboard-list fa-fw"
      url: /log/
    - label: " About"
      icon: "fa fa-paw fa-fw"
      url: /about/

# Site Footer
footer:
  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://github.com/s975188062"
#    - label: "Facebook"
#      icon: "fab fa-fw fa-facebook-square"
#      url: "https://github.com/s975188062"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/s975188062"
    - label: "CR Blog(友链)"
      url: "https://7988888.xyz/"
#    - label: "Bitbucket"
#      icon: "fab fa-fw fa-bitbucket"
#      url: "https://github.com/s975188062"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://github.com/s975188062"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /_editing
  - /.MWebMetaData
  - /_source
  - /_site
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
